#17: Added 'map' method implementation
dgroup/enumerable4j pull request #22
Opened 2021-03-07 15:06 UTC by smithros

#17: Added 'map' method implementation
Not sure about `Enumerable<T> map(Function<T, T> fnc);` signature, maybe you have any suggestions?

2021-03-09 20:55 UTC, dgroup requested changes

2021-03-09 20:56 UTC, dgroup commented on src/main/java/io/dgroup/enumerable4j/EnumerableOf.java
> +    public final Enumerable<T> map(final Function<T, T> fnc) {
И добавь плиз документацию по этому методу в `readme.md`

2021-03-09 21:06 UTC, smithros commented on src/main/java/io/dgroup/enumerable4j/EnumerableOf.java
> +    public final Enumerable<T> map(final Function<T, T> fnc) {
> 
> 
> Используй вот это
> 
> ```java
> public final Enumerable<Y> map(final Function<T, Y> fnc) {
> ...
> ```

это ведь перечит нашему интерфейсу, нет?

2021-03-10 19:01 UTC, merged

2021-03-10 19:01 UTC, rultor commented
> @rultor merge

@dgroup Done! FYI, the full log is [here](https://www.rultor.com/t/24260-795913631) (took me 2min)