Add Joined class
dgroup/enumerable4j pull request #76
Opened 2021-05-23 21:48 UTC by dykov

2021-05-23 22:42 UTC, dgroup commented on src/main/java/io/github/dgroup/enumerable4j/Joined.java
> +        this.prd = val -> true;
```java
this.fnc = val -> {
    ... //
}

...
     public boolean test(final X val) {
           return this.fnc.apply(val);
     }
```

2021-05-23 22:46 UTC, dgroup commented on src/main/java/io/github/dgroup/enumerable4j/Joined.java
> +    public Joined(final Predicate<X> first, final Predicate<X>... other) {
Please add and use in all places in Enumerable interface

2021-05-23 22:49 UTC, dgroup requested changes

2021-05-23 22:49 UTC, dgroup commented on src/main/java/io/github/dgroup/enumerable4j/Joined.java
> +    public Joined(final Predicate<X> first, final Predicate<X>... other) {
Please add and use in all places in Enumerable interface

2021-05-23 22:49 UTC, dgroup commented on src/main/java/io/github/dgroup/enumerable4j/Joined.java
> +        this.prd = val -> true;
```java
    private final Function<X, Boolean> fnc;

     public Joined(final Predicate<X> first, final Predicate<X> ... other) {
         this.fnc = val -> {
             ... //
         }
     }

     @Override
     public boolean test(final X val) {
           return this.fnc.apply(val);
     }
```

2021-05-24 17:19 UTC, dykov commented
@dgroup , please check propesed API

2021-05-25 19:24 UTC, dgroup approved these changes

2021-05-25 19:25 UTC, dgroup commented
@rultor merge

2021-05-25 19:27 UTC, rultor commented
> @rultor merge 

@dgroup OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24547-848200397)

2021-05-25 19:29 UTC, merged

2021-05-25 19:29 UTC, rultor commented
> @rultor merge 

@dgroup Done! FYI, the full log is [here](https://www.rultor.com/t/24547-848200397) (took me 2min)